{
 "title": "Expenses",
 "time": { "from": "now-13M", "to": "now" },
 "templating": {
  "list": [
   { "name": "pir_months", "label": "PIR months", "query": "1, 3, 6, 12" },
   {
    "name": "category",
    "query": "select distinct category from debit where time >= $__timeFrom() and time < $__timeTo()"
   },
   {
    "name": "merchant",
    "query": "select distinct merchant_name from debit where time >= $__timeFrom() and time < $__timeTo() and category in ([[category]])"
   },
   {
    "name": "receipt_item",
    "query": "select distinct name from shopping_receipt_items i inner join debit d on i.shopping_receipt_id = d.id where d.time >= $__timeFrom() and d.time < $__timeTo() order by name"
   }
  ]
 },
 "panels": [
  {
   "title": "Inflation rate over past [[pir_months]] months",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "with s as (select distinct on (id, time) id, time, account_amount\n           from debit d\n           left join shopping_receipt_items i on d.id = i.shopping_receipt_id\n           where category in ([[category]])\n             and merchant_name in ([[merchant]])\n             and (i.name in ([[receipt_item]]) or '__all__' in ([[receipt_item]]))),\n     t as (select date_trunc('month', time) as time,\n                  sum(account_amount)       as amount\n           from s\n           group by 1\n           order by 1),\n     u as (select time, amount, avg(amount) over (order by time rows between [[pir_months]] preceding and 1 preceding) as avg_amount from t)\nselect time, (amount - avg_amount) / avg_amount as pir\nfrom u\nwhere time >= $__timeFrom()::timestamp - '1 month'::interval and time < $__timeTo()"
    },
    {
     "rawSql": "with s as (select distinct on (id, time) id, time, account_amount\n           from debit d\n           left join shopping_receipt_items i on d.id = i.shopping_receipt_id\n           where category in ([[category]])\n             and merchant_name in ([[merchant]])\n             and (i.name in ([[receipt_item]]) or '__all__' in ([[receipt_item]]))),\n     t as (select date_trunc('month', time) as time,\n                  sum(account_amount)       as amount\n           from s\n           group by 1\n           order by 1),\n     u as (select time, amount, avg(amount) over (order by time rows between [[pir_months]] preceding and 1 preceding) as avg_amount from t)\nselect time, amount, avg_amount\nfrom u\nwhere time >= $__timeFrom()::timestamp - '1 month'::interval and time < $__timeTo()"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "with s as (select distinct on (id, time) id, time, category, account_amount\n           from debit d\n           left join shopping_receipt_items i on d.id = i.shopping_receipt_id\n           where category in ([[category]])\n             and merchant_name in ([[merchant]])\n             and (i.name in ([[receipt_item]]) or '__all__' in ([[receipt_item]])))\nselect date_trunc('month', time) as time, category, sum(account_amount) as amount\nfrom s\ngroup by 1, 2\norder by 1, 3 desc"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with s as (select distinct on (id, time) id, time, category, account_amount\n           from debit d\n           left join shopping_receipt_items i on d.id = i.shopping_receipt_id\n           where category in ([[category]])\n             and merchant_name in ([[merchant]])\n             and (i.name in ([[receipt_item]]) or '__all__' in ([[receipt_item]]))),\n     t as (select date_trunc('month', time) as time,\n                  category,\n                  sum(account_amount)       as amount\n           from s\n           group by 1, 2\n           order by 2, 1),\n     prev as (select *\n              from t\n              where date_trunc('month', time) = date_trunc('month', now() - (case when date_part('day', now()) >= 15 then '1 month' else '2 months' end)::interval)),\n     curr as (select *\n              from t\n              where date_trunc('month', time) = date_trunc('month', now() - (case when date_part('day', now()) >= 15 then '0' else '1 month' end)::interval)),\n     cmp as (select coalesce(prev.category, curr.category) as category,\n                    coalesce(prev.amount, 0)               as prev_amount,\n                    coalesce(curr.amount, 0)               as curr_amount\n             from prev\n                      full join curr on prev.category = curr.category)\nselect 'All' as category, sum(prev_amount) as last_month, sum(curr_amount) as curr_month\nfrom cmp\nunion all\n(select category, prev_amount as last_month, curr_amount as curr_month\n from cmp\n order by curr_amount desc, prev_amount desc)"
    }
   ]
  },
  {
   "title": "Merchants",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with s as (select distinct on (id, time) id, time, coalesce(merchant_name, description) as merchant_name, account_amount\n           from debit d\n           left join shopping_receipt_items i on d.id = i.shopping_receipt_id\n           where category in ([[category]])\n             and merchant_name in ([[merchant]])\n             and (i.name in ([[receipt_item]]) or '__all__' in ([[receipt_item]]))),\n     t as (select date_trunc('month', time) as time,\n                  merchant_name,\n                  sum(account_amount)       as amount,\n                  avg(account_amount)       as avg_amount\n           from s\n           group by 1, 2\n           order by 2, 1),\n     prev as (select *\n              from t\n              where date_trunc('month', time) = date_trunc('month', now() - (case when date_part('day', now()) >= 15 then '1 month' else '2 months' end)::interval)),\n     curr as (select *\n              from t\n              where date_trunc('month', time) = date_trunc('month', now() - (case when date_part('day', now()) >= 15 then '0' else '1 month' end)::interval)),\n     cmp as (select coalesce(prev.merchant_name, curr.merchant_name) as merchant_name,\n                    coalesce(prev.amount, 0)                         as prev_amount,\n                    coalesce(curr.amount, 0)                         as curr_amount,\n                    curr.avg_amount                                  as avg_amount\n             from prev\n                      full join curr on prev.merchant_name = curr.merchant_name)\nselect 'All' as merchant_name, sum(prev_amount) as \"last\", sum(curr_amount) as \"curr\", avg(avg_amount) as \"avg\"\nfrom cmp\nunion all\n(select merchant_name, prev_amount as \"last\", curr_amount as \"curr\", avg_amount as \"avg\"\n from cmp\n order by curr_amount desc, prev_amount desc)"
    }
   ]
  },
  {
   "title": "Items",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with t as (select date_trunc('month', d.time) as time,\n                  i.name as item_name,\n                  sum(i.sum) as amount\n           from debit d\n           inner join shopping_receipt_items i on d.id = i.shopping_receipt_id\n           where category in ([[category]])\n             and coalesce(merchant_name, description) in ([[merchant]])\n             and (i.name in ([[receipt_item]]) or '__all__' in ([[receipt_item]]))\n             and date_trunc('month', time) > date_trunc('month', now() - '3 months'::interval)\n           group by 1, 2\n           order by 2, 1),\n     prev as (select *\n              from t\n              where date_trunc('month', time) = date_trunc('month', now() - (case when date_part('day', now()) >= 15 then '1 month' else '2 months' end)::interval)),\n     curr as (select *\n              from t\n              where date_trunc('month', time) = date_trunc('month', now() - (case when date_part('day', now()) >= 15 then '0' else '1 month' end)::interval)),\n     cmp as (select coalesce(prev.item_name, curr.item_name) as item_name,\n                    coalesce(prev.amount, 0)                         as prev_amount,\n                    coalesce(curr.amount, 0)                         as curr_amount\n             from prev\n                      full join curr on prev.item_name = curr.item_name)\nselect 'All' as item_name, sum(prev_amount) as \"last\", sum(curr_amount) as \"curr\"\nfrom cmp\nunion all\n(select item_name, prev_amount as \"last\", curr_amount as \"curr\"\n from cmp\n order by curr_amount desc, prev_amount desc)"
    }
   ]
  }
 ]
}