{
 "title": "Overview",
 "time": { "from": "now-13M", "to": "now" },
 "templating": {
  "list": [
   { "name": "income_months", "query": "1, 2, 4, 6, 12, 18, 24, 36, 48" },
   { "name": "users", "query": "Имя Ф." }
  ]
 },
 "panels": [
  {
   "title": "Balance",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with t as (select a.name || ' (' || account_currency || ')' as account,\n                  sum(account_amount * (case when o.type = 'Debit' then -1 else 1 end)) as balance\n           from operations o\n                    inner join accounts a on a.id = o.account_id\n           where status != 'FAILED' and debiting_time is not null\n           group by 1\n           order by 1)\nselect * from t\nwhere t.balance != 0\nunion all\nselect 'ИТОГО (' || account_currency || ')' as account,\n       sum(account_amount * (case when o.type = 'Debit' then -1 else 1 end)) as balance\nfrom operations o inner join accounts a on a.id = o.account_id\nwhere a.name not like 'Вклад%' and debiting_time is not null\ngroup by account"
    }
   ]
  },
  {
   "title": "Income (RUB)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "with t as (select date_trunc('month', time) as time, sum(account_amount) as amount\n           from operations o\n           where status != 'FAILED'\n            and type = 'Credit'\n            and debiting_time is not null\n            and not (description in ([[users]]) and merchant_name in ('Тинькофф банк', 'Входящий перевод'))\n            and description not in ('Перевод между счетами', 'Перевод с карты')\n            and category in ('Бонусы', 'Пополнения', 'Переводы', 'Проценты', 'Зарплата')\n            and account_currency = 'RUB'\n           group by 1),\n     v as (select time, amount, avg(amount) over (order by time rows between [[income_months]] preceding and 1 preceding) as avg_amount from t)\nselect time, (amount - avg_amount) / avg_amount as pir\nfrom v\norder by 1;"
    },
    {
     "rawSql": "with t as (select date_trunc('month', time) as time, sum(account_amount) as amount\n           from operations o\n           where status != 'FAILED'\n            and type = 'Credit'\n            and debiting_time is not null\n            and not (description in ([[users]]) and merchant_name in ('Тинькофф банк', 'Входящий перевод'))\n            and description not in ('Перевод между счетами', 'Перевод с карты')\n            and category in ('Бонусы', 'Пополнения', 'Переводы', 'Проценты', 'Зарплата')\n            and account_currency = 'RUB'\n           group by 1),\n     v as (select time, amount, avg(amount) over (order by time rows between [[income_months]] preceding and 1 preceding) as avg_amount from t)\nselect time, amount, avg_amount\nfrom v\norder by 1;"
    }
   ]
  },
  {
   "title": "Stocks",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with t as (select tp.currency,\n                  tp.username,\n                  sum(buy_price * quantity) / sum(quantity) as buy_price,\n                  sum(quantity)                             as quantity,\n                  sum(value * quantity) / sum(quantity)     as price\n           from trading_positions tp\n                    inner join (select u.ticker, u.value\n                                from purchased_securities u\n                                         inner join (select ticker, max(time) as time from purchased_securities group by ticker) v\n                                                    using (ticker, time)) w\n                               using (ticker)\n           where tp.sell_time is null\n           group by tp.currency, tp.username),\n     x as (select currency,\n                  username,\n                  sum(1.003 * buy_price * quantity)                                                                          as buy,\n                  sum((0.997 * price - 0.13 * case when price - buy_price > 0 then price - buy_price else 0 end) * quantity) as sell\n           from t\n           group by currency, username)\nselect *\nfrom (select username || ' (' || currency || ')' as account,\n             sum(buy)                        as buy,\n             sum(sell)                       as sell,\n             sum(sell - buy)                 as profit,\n             sum(sell) / sum(buy) - 1        as pct\n      from x\n      group by 1\n      order by 1) as y\nunion all\n(select 'ИТОГО (' || currency || ')' as account,\n        sum(buy)                 as buy,\n        sum(sell)                as sell,\n        sum(sell - buy)          as profit,\n        sum(sell) / sum(buy) - 1 as pct\n from x\n group by 1\n order by 1)"
    }
   ]
  },
  {
   "title": "Debit / credit RUB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "select date_trunc('month', time)                                           as time,\n       sum(account_amount * (case when type = 'Credit' then 1 else 0 end)) as credit,\n       sum(account_amount * (case when type = 'Debit' then -1 else 0 end)) as debit\nfrom operations\nwhere coalesce(merchant_name, '') not in ('Внутрибанковский перевод', 'Вывод с брокерского счета', 'Пополнение брокерского счета')\n  and debiting_time is not null\n  and not (description in ([[users]]) and merchant_name in ('Тинькофф банк', 'Входящий перевод'))\n  and date_trunc('month', time) >= $__timeFrom() and date_trunc('month', time) < $__timeTo()\n  and status != 'FAILED'\n  and account_currency = 'RUB'\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Debit / credit USD",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select date_trunc('month', time)                                           as time,\n       sum(account_amount * (case when type = 'Credit' then 1 else 0 end)) as credit,\n       sum(account_amount * (case when type = 'Debit' then -1 else 0 end)) as debit\nfrom operations\nwhere coalesce(merchant_name, '') not in ('Внутрибанковский перевод', 'Вывод с брокерского счета', 'Пополнение брокерского счета')\n  and debiting_time is not null\n  and not (description in ([[users]]) and merchant_name in ('Тинькофф банк', 'Входящий перевод'))\n  and date_trunc('month', time) >= $__timeFrom() and date_trunc('month', time) < $__timeTo()\n  and status != 'FAILED'\n  and account_currency = 'USD'\ngroup by 1\norder by 1"
    }
   ]
  }
 ]
}