on:
  push:
    branches: [ master ]
    tags: [ '**' ]
name: publish
jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker build -t ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF##*/} --build-arg VERSION=${GITHUB_REF##*/} .
          docker push ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF##*/}
